sudo: false
language: node_js
node_js:
- '6'
script: gulp travis
env:
  global:
    secure: Nv9IBrcMhYzN6i4rTQljx6ASL7rGx54Ce6G0iXTF9g7/xwZpNjFaOPZwuu+Qxg5HLLgpul1wtLFayXZB2ONxQOUwejWYaHcLOlCbTp9ApJdgyf6+4EAdhGPKCw03iJS2vGCHks5inIhlNqRk3ZgNqdwfkN9OYZwtWDZj1JOXvlC2SXWFNq9p0xbyVb+2vNJw69ROSei+kFfd349ERusxcgrro5eLmALeGfg0LzGjN65z3WFpJFL2njsfcVWPcW8XUa2gnP4rn1sxgLAKhGjwYG10W4/lR2XXcVx5pKXZclZbn6B5cDd5/qDTB4tKayX2O7cgmOA4MARrAEmmlzb5T0NuPI5W816vA4mmq3p7Onl2MgBpuptXlWdTvdDL20wZkUBRjAaOaY2i/Muxj0aHAtW8q+UhchKphmCakaJIJeUPRrgttz1ONMEvFz/1J8Cq6RDdKOBcTa4VsqFW3VBPc0AWkVJcIAszhPVXWhnzVVwEkV7DYfPS1TZxUTQEpzCQXfX9LYjRBS7psRdH7oH43tisOJuxLCVsYfrCu5gAY5w2H3Z5u6rULGPnEU35JChN2uNtSPCfOhDBzTK9sksARDrEcXp/jp6bjvZNT5c0SwKGivw49OSDuOMxwwVczMJrTOveLyo9wG2ltYgllS/Bf1w9G0uCzTGywi7Mv8+ULmI=
